apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nalut.de
  namespace: app
spec:
  secretName: nalut.de
  issuerRef:
    name: letsencrypt-wcard
    kind: Issuer
    group: cert-manager.io
  commonName: "*.nalut.de"
  dnsNames:
    - "nalut.de"
    - "*.nalut.de"