apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-wcard
  namespace: ingress
spec:
  acme:
    email: jan@ubari.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-wcard-private
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: ingress-secret
              key: DO_API_KEY
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nalut.de
  namespace: ingress
spec:
  secretName: nalut.de
  issuerRef:
    name: letsencrypt-wcard
    kind: Issuer
    group: cert-manager.io
  commonName: "*.nalut.de"
  dnsNames:
    - "nalut.de"
    - "*.nalut.de"