apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nginx-ingress.yaml
- external-dns.yaml
- https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.yaml
