apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: test
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - "*.nalut.de"
    secretName: tls-nalut.de
  rules:
    - host: whoami.nalut.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-app
                port:
                  number: 80
